use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    fihi_api::run()
}
